# Generated by Django 6.0 on 2025-12-12 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='angkatan',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Angkatan'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nomor_hp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nomor HP/WhatsApp'),
        ),
        migrations.AlterField(
            model_name='user',
            name='npm_nip',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='NPM/NIP'),
        ),
    ]
