# Generated by Django 6.0 on 2025-12-12 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_angkatan_alter_user_nomor_hp_alter_user_npm_nip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='angkatan',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Angkatan'),
        ),
    ]
