# Generated by Django 6.0 on 2025-12-12 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_angkatan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Mahasiswa', 'Mahasiswa'), ('Dosen', 'Dosen'), ('Staff', 'Staff'), ('Admin', 'Admin')], default='Mahasiswa', max_length=20, verbose_name='Role'),
        ),
    ]
