# Generated by Django 6.0 on 2025-12-12 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_message_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='dokumen_pendukung',
            field=models.FileField(blank=True, help_text='Upload dokumen pendukung (PDF, DOC, DOCX)', null=True, upload_to='dokumen_booking/', verbose_name='Dokumen Pendukung'),
        ),
        migrations.AddField(
            model_name='booking',
            name='jumlah_tamu',
            field=models.PositiveIntegerField(default=1, help_text='Jumlah peserta/tamu yang akan hadir', verbose_name='Jumlah Tamu'),
        ),
    ]
