# Generated by Django 6.0 on 2025-12-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_booking_dokumen_pendukung_booking_jumlah_tamu'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='deskripsi',
            field=models.TextField(blank=True, help_text='Deskripsi lengkap tentang ruangan ini', verbose_name='Deskripsi Ruangan'),
        ),
        migrations.AddField(
            model_name='room',
            name='peraturan',
            field=models.TextField(blank=True, help_text='Peraturan dan ketentuan penggunaan ruangan (pisahkan dengan baris baru)', verbose_name='Peraturan Penggunaan'),
        ),
    ]
