# Generated by Django 6.0 on 2025-12-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_room_deskripsi_room_peraturan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, verbose_name='Nama')),
                ('role', models.CharField(help_text='Contoh: Mahasiswa Teknik Informatika, Dosen FKIP, Staff Akademik', max_length=100, verbose_name='Jabatan/Role')),
                ('foto', models.ImageField(blank=True, help_text='Foto profil (opsional, ukuran rekomendasi: 100x100px)', null=True, upload_to='testimonials/', verbose_name='Foto')),
                ('content', models.TextField(help_text='Testimoni tentang pengalaman menggunakan SmartSpace UPY', verbose_name='Isi Testimoni')),
                ('rating', models.PositiveIntegerField(default=5, help_text='Rating 1-5 bintang', verbose_name='Rating')),
                ('is_active', models.BooleanField(default=True, help_text='Centang untuk menampilkan di homepage', verbose_name='Aktif')),
                ('order', models.PositiveIntegerField(default=0, help_text='Urutan tampil (angka kecil tampil duluan)', verbose_name='Urutan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Testimoni',
                'verbose_name_plural': 'Testimoni',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
