# Generated by Django 6.0 on 2025-12-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_testimonial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at'], 'verbose_name': 'Pesan', 'verbose_name_plural': 'Pesan'},
        ),
        migrations.AddField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, help_text='File lampiran (gambar, dokumen, dll)', null=True, upload_to='message_attachments/', verbose_name='Lampiran'),
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('user_to_admin', 'User ke Admin'), ('admin_to_user', 'Admin ke User')], default='admin_to_user', max_length=20, verbose_name='Tipe Pesan'),
        ),
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Subjek'),
        ),
    ]
