# Generated by Django 6.0 on 2025-12-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_booking_status_pinnedconversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='larangan',
            field=models.TextField(blank=True, help_text='Hal-hal yang TIDAK BOLEH dilakukan di ruangan ini (pisahkan dengan baris baru)', verbose_name='Hal yang Dilarang ❌'),
        ),
        migrations.AlterField(
            model_name='room',
            name='peraturan',
            field=models.TextField(blank=True, help_text='Hal-hal yang BOLEH dilakukan di ruangan ini (pisahkan dengan baris baru)', verbose_name='Hal yang Diperbolehkan ✅'),
        ),
    ]
