# Generated by Django 6.0 on 2025-12-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_larangan_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='fasilitas',
            field=models.TextField(blank=True, help_text='Daftar fasilitas ruangan (satu fasilitas per baris, tekan Enter untuk menambah)', verbose_name='Fasilitas'),
        ),
    ]
