# Generated by Django 6.0 on 2025-12-15 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_change_fasilitas_to_textfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fakultas',
            field=models.CharField(blank=True, choices=[('FKIP', 'Fakultas Keguruan dan Ilmu Pendidikan'), ('FEB', 'Fakultas Ekonomi dan Bisnis'), ('FT', 'Fakultas Teknik'), ('FIKES', 'Fakultas Ilmu Kesehatan'), ('FISIP', 'Fakultas Ilmu Sosial dan Ilmu Politik'), ('FAI', 'Fakultas Agama Islam'), ('FPSI', 'Fakultas Psikologi')], max_length=20, null=True, verbose_name='Fakultas'),
        ),
        migrations.AlterField(
            model_name='room',
            name='nomor_ruangan',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nama Ruangan'),
        ),
    ]
