# Generated by Django 6.0 on 2025-12-15 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_fakultas_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='foto_drive_id',
            field=models.CharField(blank=True, help_text='Alternatif: masukkan ID file dari Google Drive (contoh: 1aBcDeFgHiJkLmNoPqRs)', max_length=100, null=True, verbose_name='Google Drive ID'),
        ),
        migrations.AddField(
            model_name='room',
            name='foto_url',
            field=models.URLField(blank=True, help_text='Alternatif: masukkan URL langsung ke gambar', null=True, verbose_name='URL Gambar'),
        ),
        migrations.AlterField(
            model_name='room',
            name='foto_ruangan',
            field=models.ImageField(blank=True, null=True, upload_to='ruangan/', verbose_name='Upload Foto'),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('approve', 'Approve'), ('reject', 'Reject')], max_length=20, verbose_name='Aksi')),
                ('model_name', models.CharField(max_length=50, verbose_name='Model')),
                ('object_id', models.PositiveIntegerField(verbose_name='Object ID')),
                ('object_repr', models.CharField(max_length=200, verbose_name='Object')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='Perubahan')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, verbose_name='Nama')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('category', models.CharField(choices=[('kritik', 'Kritik'), ('saran', 'Saran'), ('lainnya', 'Lainnya')], default='saran', max_length=20, verbose_name='Kategori')),
                ('subject', models.CharField(max_length=200, verbose_name='Subjek')),
                ('message', models.TextField(verbose_name='Pesan')),
                ('is_read', models.BooleanField(default=False, verbose_name='Sudah Dibaca')),
                ('admin_response', models.TextField(blank=True, verbose_name='Respon Admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Kritik & Saran',
                'verbose_name_plural': 'Kritik & Saran',
                'ordering': ['-created_at'],
            },
        ),
    ]
