# Generated by Django 6.0 on 2025-12-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_feedback_activitylog_room_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fakultas',
            field=models.CharField(blank=True, choices=[('FST', 'Fakultas Sains Dan Teknologi'), ('FP', 'Fakultas Pertanian'), ('FBH', 'Fakultas Bisnis Dan Hukum'), ('FKIP', 'Fakultas Keguruan Dan Ilmu Pendidikan')], max_length=20, null=True, verbose_name='Fakultas'),
        ),
    ]
