# Generated by Django 6.0 on 2025-12-16 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='average_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='Rating Rata-rata'),
        ),
        migrations.AddField(
            model_name='room',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0, verbose_name='Jumlah Review'),
        ),
        migrations.CreateModel(
            name='RoomComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(help_text='Rating 1-5 bintang', verbose_name='Rating')),
                ('comment', models.TextField(help_text='Komentar tentang ruangan', verbose_name='Komentar')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Disetujui')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.room', verbose_name='Ruangan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_comments', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Komentar Ruangan',
                'verbose_name_plural': 'Komentar Ruangan',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'room')},
            },
        ),
    ]
