# Generated by Django 6.0 on 2025-12-16 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_room_average_rating_room_total_reviews_roomcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='dokumen_pendukung',
            field=models.FileField(blank=True, help_text='Upload dokumen pendukung (hanya PDF)', null=True, upload_to='dokumen_booking/', verbose_name='Dokumen Pendukung'),
        ),
        migrations.CreateModel(
            name='RoomReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keterangan', models.TextField(help_text='Deskripsikan masalah atau keluhan terkait ruangan ini', verbose_name='Keterangan')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Sudah Ditangani')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.room', verbose_name='Ruangan')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_reports', to=settings.AUTH_USER_MODEL, verbose_name='Pelapor')),
            ],
            options={
                'verbose_name': 'Laporan Ruangan',
                'verbose_name_plural': 'Laporan Ruangan',
                'ordering': ['-created_at'],
            },
        ),
    ]
