# Generated by Django 6.0 on 2025-12-17 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_roomreport_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='maintenance_end_date',
            field=models.DateField(blank=True, help_text='Perkiraan tanggal ruangan tersedia kembali (opsional)', null=True, verbose_name='Estimasi Selesai'),
        ),
        migrations.AddField(
            model_name='room',
            name='maintenance_note',
            field=models.TextField(blank=True, help_text='Alasan atau detail perbaikan (opsional)', verbose_name='Catatan Perbaikan'),
        ),
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('available', 'Tersedia'), ('maintenance', 'Dalam Perbaikan'), ('unavailable', 'Tidak Tersedia')], default='available', max_length=20, verbose_name='Status Ruangan'),
        ),
    ]
