"""
Django settings for smartspaceupy project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import dj_database_url
import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-#th20x2_bl7c=ji_9g72#4y5u%vx)o@sqjg^+_&d)qs7(-+lex')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() in ('true', '1', 'yes')

# Allowed hosts for production
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# CSRF trusted origins for production
CSRF_TRUSTED_ORIGINS = os.getenv('CSRF_TRUSTED_ORIGINS', 'http://localhost:8000,http://127.0.0.1:8000').split(',')


# Application definition

INSTALLED_APPS = [
    'unfold',  # Django Unfold - must be before django.contrib.admin
    'unfold.contrib.filters',  # Optional: better filters
    'unfold.contrib.forms',  # Optional: better forms
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cloudinary',
    'cloudinary_storage',
    'core',
]

# Django Unfold Admin Configuration
from django.templatetags.static import static
from django.urls import reverse_lazy

UNFOLD = {
    "SITE_TITLE": "SmartSpace UPY",
    "SITE_HEADER": "SmartSpace Admin",
    "SITE_SYMBOL": "space_dashboard",  # Material Symbols icon
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "ENVIRONMENT": "development",
    "COLORS": {
        "primary": {
            "50": "#EFF6FF",
            "100": "#DBEAFE",
            "200": "#BFDBFE",
            "300": "#93C5FD",
            "400": "#60A5FA",
            "500": "#3B82F6",  # Primary color (Tailwind Blue-500)
            "600": "#2563EB",
            "700": "#1D4ED8",
            "800": "#1E40AF",
            "900": "#1E3A8A",
            "950": "#172554",
        },
    },
    "SIDEBAR": {
        "show_search": True,  # Re-enable search
        "show_all_applications": False,  # Hide All applications section
        "navigation": [
            {
                "title": "Dashboard",
                "separator": False,
                "items": [
                    {
                        "title": "Dashboard",
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:index"),
                    },
                ],
            },
            {
                "title": "Manajemen User",
                "separator": True,
                "items": [
                    {
                        "title": "Users",
                        "icon": "people",
                        "link": reverse_lazy("admin:core_user_changelist"),
                    },
                ],
            },
            {
                "title": "Manajemen Ruang",
                "separator": True,
                "items": [
                    {
                        "title": "Ruangan",
                        "icon": "meeting_room",
                        "link": reverse_lazy("admin:core_room_changelist"),
                    },
                    {
                        "title": "Peminjaman",
                        "icon": "event_available",
                        "link": reverse_lazy("admin:core_booking_changelist"),
                        "badge": "core.admin_views.get_pending_booking_count",
                    },
                    {
                        "title": "Wishlist",
                        "icon": "favorite",
                        "link": reverse_lazy("admin:core_wishlist_changelist"),
                    },
                ],
            },
            {
                "title": "Komunikasi",
                "separator": True,
                "items": [
                    {
                        "title": "Chat User",
                        "icon": "chat",
                        "link": "/admin/chat/",
                    },
                    {
                        "title": "Kritik & Saran",
                        "icon": "feedback",
                        "link": reverse_lazy("admin:core_feedback_changelist"),
                    },
                ],
            },
            {
                "title": "Ulasan",
                "separator": True,
                "items": [
                    {
                        "title": "Komentar Ruangan",
                        "icon": "rate_review",
                        "link": reverse_lazy("admin:core_roomcomment_changelist"),
                    },
                ],
            },
            {
                "title": "Konten Website",
                "separator": True,
                "items": [
                    {
                        "title": "Testimoni",
                        "icon": "format_quote",
                        "link": reverse_lazy("admin:core_testimonial_changelist"),
                    },
                ],
            },
            {
                "title": "Monitoring",
                "separator": True,
                "items": [
                    {
                        "title": "Activity Log",
                        "icon": "history",
                        "link": reverse_lazy("admin:core_activitylog_changelist"),
                    },
                ],
            },
            {
                "title": "Bantuan",
                "separator": True,
                "items": [
                    {
                        "title": "Admin Shortcut",
                        "icon": "keyboard",
                        "link": "/admin/shortcuts/",
                    },
                ],
            },
        ],
    },
    "SCRIPTS": [
        lambda request: static("admin/js/admin_shortcuts.js"),
    ],
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Static files for production
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'smartspaceupy.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'smartspaceupy.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Use DATABASE_URL from environment if available (Railway/Production)
# Otherwise fall back to SQLite (local development)
DATABASE_URL = os.getenv('DATABASE_URL')

if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL)
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Jakarta'

USE_I18N = True

USE_TZ = True

# Custom date/time formats for Indonesian locale (24-hour format)
DATE_FORMAT = 'd M Y'
TIME_FORMAT = 'H:i'
DATETIME_FORMAT = 'd M Y, H:i'
SHORT_DATE_FORMAT = 'd/m/Y'
SHORT_DATETIME_FORMAT = 'd/m/Y H:i'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'core' / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'  # For production (collectstatic)

# Media files (Uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Cloudinary Configuration (for production media storage)
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.getenv('CLOUDINARY_CLOUD_NAME', ''),
    'API_KEY': os.getenv('CLOUDINARY_API_KEY', ''),
    'API_SECRET': os.getenv('CLOUDINARY_API_SECRET', ''),
    'SECURE': True,
    'RESOURCE_TYPE': 'auto',  # Auto-detect file type (image, raw, video)
}

# Storage configuration - Django 5.0+ uses STORAGES
if os.getenv('CLOUDINARY_CLOUD_NAME'):
    # Use Cloudinary for media files in production
    STORAGES = {
        "default": {
            "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }
else:
    # Use local filesystem for development
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }

# Custom User Model
AUTH_USER_MODEL = 'core.User'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Google Gemini AI Configuration
GEMINI_API_KEY = os.getenv('GEMINI_API_KEY', '')

# Brevo (Sendinblue) Email Configuration
BREVO_API_KEY = os.getenv('BREVO_API_KEY', '')
EMAIL_FROM = 'SmartSpace UPY <dickoadityaazhar20@gmail.com>'
EMAIL_FROM_NAME = 'SmartSpace UPY'

# Session Configuration - Expire on browser close
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # Session berakhir saat browser ditutup
SESSION_COOKIE_AGE = 86400  # 24 jam (fallback jika browser tidak ditutup)
SESSION_SAVE_EVERY_REQUEST = True  # Refresh session setiap request
